-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.custom_foods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  calories_per_100g numeric NOT NULL,
  protein_per_100g numeric NOT NULL,
  carbs_per_100g numeric NOT NULL,
  fat_per_100g numeric NOT NULL,
  fiber_per_100g numeric DEFAULT 0,
  is_vegan boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  sugar_per_100g numeric DEFAULT 0,
  saturated_fat_per_100g numeric DEFAULT 0,
  sodium_mg_per_100g numeric DEFAULT 0,
  vitamin_b12_mcg_per_100g numeric DEFAULT NULL::numeric,
  iron_mg_per_100g numeric DEFAULT NULL::numeric,
  zinc_mg_per_100g numeric DEFAULT NULL::numeric,
  calcium_mg_per_100g numeric DEFAULT NULL::numeric,
  vitamin_d_mcg_per_100g numeric DEFAULT NULL::numeric,
  omega3_g_per_100g numeric DEFAULT NULL::numeric,
  brand text,
  image_url text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT custom_foods_pkey PRIMARY KEY (id),
  CONSTRAINT custom_foods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.food_cache (
  barcode text NOT NULL,
  data jsonb NOT NULL,
  fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT food_cache_pkey PRIMARY KEY (barcode)
);
CREATE TABLE public.food_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  meal_type text NOT NULL CHECK (meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text, 'snack'::text])),
  food_name text NOT NULL,
  barcode text,
  brand text,
  serving_size_g numeric NOT NULL,
  calories numeric NOT NULL DEFAULT 0,
  protein_g numeric NOT NULL DEFAULT 0,
  carbs_g numeric NOT NULL DEFAULT 0,
  fat_g numeric NOT NULL DEFAULT 0,
  fiber_g numeric DEFAULT 0,
  sugar_g numeric DEFAULT 0,
  saturated_fat_g numeric DEFAULT 0,
  sodium_mg numeric DEFAULT 0,
  is_vegan boolean DEFAULT true,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  vitamin_b12_mcg real,
  iron_mg real,
  zinc_mg real,
  calcium_mg real,
  omega3_g real,
  vitamin_d_mcg real,
  iodine_mcg real,
  selenium_mcg real,
  vitamin_b12_known boolean NOT NULL DEFAULT false,
  iron_known boolean NOT NULL DEFAULT false,
  zinc_known boolean NOT NULL DEFAULT false,
  calcium_known boolean NOT NULL DEFAULT false,
  omega3_known boolean NOT NULL DEFAULT false,
  vitamin_d_known boolean NOT NULL DEFAULT false,
  iodine_known boolean NOT NULL DEFAULT false,
  selenium_known boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'openfoodfacts'::text,
  source_ref text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT food_log_pkey PRIMARY KEY (id),
  CONSTRAINT food_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.micronutrients_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  vitamin_b12_mcg numeric DEFAULT 0,
  iron_mg numeric DEFAULT 0,
  zinc_mg numeric DEFAULT 0,
  calcium_mg numeric DEFAULT 0,
  omega3_g numeric DEFAULT 0,
  iodine_mcg numeric DEFAULT 0,
  vitamin_d_mcg numeric DEFAULT 0,
  selenium_mcg numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT micronutrients_log_pkey PRIMARY KEY (id),
  CONSTRAINT micronutrients_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.nutrient_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  food_name_pattern text NOT NULL,
  match_type text NOT NULL CHECK (match_type = ANY (ARRAY['exact'::text, 'contains'::text])),
  vitamin_b12_mcg_per_100g numeric,
  iron_mg_per_100g numeric,
  zinc_mg_per_100g numeric,
  calcium_mg_per_100g numeric,
  vitamin_d_mcg_per_100g numeric,
  omega3_g_per_100g numeric,
  source text NOT NULL DEFAULT 'USDA'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nutrient_overrides_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  display_name text,
  height_cm numeric,
  weight_kg numeric,
  birth_date date,
  sex text CHECK (sex = ANY (ARRAY['male'::text, 'female'::text])),
  activity_level text DEFAULT 'moderate'::text CHECK (activity_level = ANY (ARRAY['sedentary'::text, 'light'::text, 'moderate'::text, 'active'::text, 'very_active'::text])),
  goal text DEFAULT 'maintain'::text CHECK (goal = ANY (ARRAY['cut'::text, 'maintain'::text, 'bulk'::text])),
  calorie_target integer,
  protein_target_g integer,
  carbs_target_g integer,
  fat_target_g integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  streak_count integer DEFAULT 0,
  last_log_date date,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text])),
  subscription_expires_at timestamp with time zone,
  stripe_customer_id text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.recipe_ingredients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipe_id uuid NOT NULL,
  food_name text NOT NULL,
  brand text,
  barcode text,
  serving_size_g numeric NOT NULL CHECK (serving_size_g > 0::numeric),
  calories_per_100g numeric DEFAULT 0,
  protein_per_100g numeric DEFAULT 0,
  carbs_per_100g numeric DEFAULT 0,
  fat_per_100g numeric DEFAULT 0,
  fiber_per_100g numeric DEFAULT 0,
  sugar_per_100g numeric DEFAULT 0,
  saturated_fat_per_100g numeric DEFAULT 0,
  sodium_mg_per_100g numeric DEFAULT 0,
  vitamin_b12_mcg_per_100g numeric,
  iron_mg_per_100g numeric,
  zinc_mg_per_100g numeric,
  calcium_mg_per_100g numeric,
  vitamin_d_mcg_per_100g numeric,
  omega3_g_per_100g numeric,
  vitamin_b12_known boolean DEFAULT false,
  iron_known boolean DEFAULT false,
  zinc_known boolean DEFAULT false,
  calcium_known boolean DEFAULT false,
  vitamin_d_known boolean DEFAULT false,
  omega3_known boolean DEFAULT false,
  is_vegan boolean DEFAULT true,
  image_url text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (id),
  CONSTRAINT recipe_ingredients_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id)
);
CREATE TABLE public.recipes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  total_servings numeric NOT NULL DEFAULT 1 CHECK (total_servings > 0::numeric),
  image_url text,
  is_vegan boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recipes_pkey PRIMARY KEY (id),
  CONSTRAINT recipes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.supplement_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  supplement_id uuid NOT NULL,
  date date NOT NULL,
  taken_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT supplement_logs_pkey PRIMARY KEY (id),
  CONSTRAINT supplement_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT supplement_logs_supplement_id_fkey FOREIGN KEY (supplement_id) REFERENCES public.supplements(id)
);
CREATE TABLE public.supplements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  nutrient_key text,
  dose_amount numeric NOT NULL,
  dose_unit text NOT NULL,
  frequency text DEFAULT 'daily'::text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  emoji text,
  CONSTRAINT supplements_pkey PRIMARY KEY (id),
  CONSTRAINT supplements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.weight_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  weight_kg numeric NOT NULL CHECK (weight_kg > 0::numeric AND weight_kg < 500::numeric),
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT weight_logs_pkey PRIMARY KEY (id),
  CONSTRAINT weight_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);